/* ============================================================
   PANTRY-TO-OVEN — SEED DATA
   Pre-loads 21 recipes across all 7 categories on first visit.
   Call initSeedData() once on app load.
   ============================================================ */

const SEED_RECIPES = [

  /* ══════════════════════════════════════════════
     CAKES (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_001',
    title: 'Classic Vanilla Sponge Cake',
    category: 'Cakes',
    difficulty: 'Beginner',
    prepTime: 20,
    bakeTime: 35,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'A light, fluffy vanilla sponge that melts in your mouth. Perfect for birthdays or a cozy afternoon tea.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'granulated sugar',     qty: '1½ cups' },
      { name: 'unsalted butter',      qty: '½ cup (softened)' },
      { name: 'large eggs',           qty: '3' },
      { name: 'whole milk',           qty: '1 cup' },
      { name: 'baking powder',        qty: '2 tsp' },
      { name: 'vanilla extract',      qty: '2 tsp' },
      { name: 'salt',                 qty: '½ tsp' },
    ],
    steps: [
      { instruction: 'Preheat oven to 175°C (350°F). Grease two 9-inch round cake pans and dust with flour.', tip: 'Make sure your oven is fully preheated before baking for an even rise.' },
      { instruction: 'In a large bowl, cream butter and sugar together using a hand mixer on medium speed until pale and fluffy, about 4–5 minutes.', tip: 'Cold butter will not cream properly — always use room temperature butter.' },
      { instruction: 'Add eggs one at a time, beating well after each addition. Mix in vanilla extract.', tip: 'Room temperature eggs incorporate more easily into the batter.' },
      { instruction: 'In a separate bowl, whisk together flour, baking powder, and salt.', tip: 'Sifting the flour gives a lighter, more even texture.' },
      { instruction: 'Alternately add the flour mixture and milk to the butter mixture, starting and ending with flour. Mix until just combined — do not overmix.', tip: 'Overmixing develops gluten and makes the cake tough.' },
      { instruction: 'Divide batter evenly between the prepared pans. Bake for 30–35 minutes until a toothpick inserted in the centre comes out clean.', tip: 'Do not open the oven door in the first 20 minutes.' },
      { instruction: 'Cool in pans for 10 minutes, then turn out onto a wire rack. Cool completely before frosting.', tip: 'Frosting a warm cake will melt the icing — patience pays off!' },
    ],
    nutrition: { calories: 320, protein: '5g', carbs: '48g', fat: '12g', fiber: '1g', sugar: '28g' },
    views: 42, saves: 18,
    createdAt: '2025-01-10T08:00:00.000Z',
  },

  {
    id: 'r_seed_002',
    title: 'Decadent Red Velvet Cake',
    category: 'Cakes',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 35,
    servings: 12,
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&q=80',
    description: 'Vibrant crimson layers with a subtle cocoa flavour, topped with silky cream cheese frosting. A show-stopper for any occasion.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2½ cups' },
      { name: 'granulated sugar',     qty: '1½ cups' },
      { name: 'unsalted butter',      qty: '½ cup (softened)' },
      { name: 'large eggs',           qty: '2' },
      { name: 'buttermilk',           qty: '1 cup' },
      { name: 'cocoa powder',         qty: '2 tbsp' },
      { name: 'red food colouring',   qty: '2 tbsp' },
      { name: 'baking soda',          qty: '1 tsp' },
      { name: 'white vinegar',        qty: '1 tsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: '1 tsp' },
      { name: 'cream cheese',         qty: '250g (for frosting)' },
      { name: 'powdered sugar',       qty: '2 cups (for frosting)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 175°C (350°F). Grease and flour two 9-inch round cake pans.', tip: 'Line the bottom with parchment paper for easy release.' },
      { instruction: 'Cream butter and sugar until light and fluffy, about 5 minutes. Beat in eggs one at a time, then mix in vanilla.', tip: '' },
      { instruction: 'In a small bowl, mix cocoa powder and red food colouring into a paste. Add to the butter mixture and blend well.', tip: 'Gel food colouring gives a more vibrant colour than liquid.' },
      { instruction: 'Alternate adding flour and buttermilk to the mixture, beginning and ending with flour. Mix until smooth.', tip: '' },
      { instruction: 'In a small bowl, combine baking soda and white vinegar — it will fizz. Gently fold this into the batter immediately.', tip: 'Do not stir vigorously — you want to preserve the lift.' },
      { instruction: 'Divide batter between pans. Bake 30–35 minutes until a toothpick comes out clean. Cool completely on wire racks.', tip: '' },
      { instruction: 'Beat cream cheese until smooth. Add powdered sugar gradually and beat until fluffy. Frost the cooled cake.', tip: 'Chill the frosted cake for 30 minutes before slicing for clean cuts.' },
    ],
    nutrition: { calories: 410, protein: '6g', carbs: '58g', fat: '18g', fiber: '1g', sugar: '42g' },
    views: 38, saves: 22,
    createdAt: '2025-01-12T08:00:00.000Z',
  },

  {
    id: 'r_seed_003',
    title: 'Dark Chocolate Lava Cake',
    category: 'Cakes',
    difficulty: 'Advanced',
    prepTime: 20,
    bakeTime: 12,
    servings: 4,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&q=80',
    description: 'Individual molten chocolate cakes with a warm, gooey centre. Pure indulgence in under 15 minutes of baking.',
    ingredients: [
      { name: 'dark chocolate (70%)', qty: '200g' },
      { name: 'unsalted butter',      qty: '100g' },
      { name: 'large eggs',           qty: '4' },
      { name: 'egg yolks',            qty: '2 extra' },
      { name: 'powdered sugar',       qty: '½ cup' },
      { name: 'all-purpose flour',    qty: '¼ cup' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: 'a pinch' },
      { name: 'cocoa powder',         qty: '2 tbsp (for dusting)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 220°C (425°F). Butter 4 ramekins generously and dust with cocoa powder, tapping out excess.', tip: 'This step is critical — the cakes must release cleanly from the ramekins.' },
      { instruction: 'Melt chocolate and butter together in a heatproof bowl over simmering water (double boiler), stirring until smooth. Remove from heat.', tip: 'Do not let the bowl touch the water — steam alone melts the chocolate.' },
      { instruction: 'In a separate bowl, whisk together whole eggs, egg yolks, and powdered sugar vigorously for 2 minutes until pale.', tip: '' },
      { instruction: 'Fold the chocolate mixture into the egg mixture. Then gently fold in flour, vanilla, and salt — do not overmix.', tip: 'A few flour streaks are fine — overmixing will toughen the outside.' },
      { instruction: 'Divide batter evenly among the prepared ramekins. At this point you can refrigerate for up to 24 hours.', tip: 'Make ahead and bake when guests arrive for stress-free hosting.' },
      { instruction: 'Bake for 10–12 minutes — the edges should be set but the centre should jiggle slightly when shaken.', tip: 'Every oven is different. Do a test with one ramekin before baking all four.' },
      { instruction: 'Run a knife around the edge, let rest 1 minute, then invert onto a plate. Serve immediately with vanilla ice cream.', tip: 'Serve within 60 seconds of inverting for maximum flow.' },
    ],
    nutrition: { calories: 520, protein: '9g', carbs: '42g', fat: '34g', fiber: '3g', sugar: '32g' },
    views: 55, saves: 30,
    createdAt: '2025-01-15T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     COOKIES (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_004',
    title: 'Chewy Chocolate Chip Cookies',
    category: 'Cookies',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 12,
    servings: 24,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80',
    description: 'Golden, crisp edges with a soft, chewy centre loaded with melty chocolate chips. The ultimate classic cookie.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2¼ cups' },
      { name: 'unsalted butter',      qty: '1 cup (softened)' },
      { name: 'granulated sugar',     qty: '¾ cup' },
      { name: 'brown sugar',          qty: '¾ cup (packed)' },
      { name: 'large eggs',           qty: '2' },
      { name: 'chocolate chips',      qty: '2 cups' },
      { name: 'baking soda',          qty: '1 tsp' },
      { name: 'vanilla extract',      qty: '2 tsp' },
      { name: 'salt',                 qty: '1 tsp' },
    ],
    steps: [
      { instruction: 'Preheat oven to 190°C (375°F). Line two baking sheets with parchment paper.', tip: '' },
      { instruction: 'Beat butter, granulated sugar, and brown sugar together until creamy, about 3 minutes. Beat in eggs and vanilla.', tip: 'Brown sugar adds chewiness; granulated sugar creates crispness.' },
      { instruction: 'Whisk flour, baking soda, and salt together. Gradually blend into the butter mixture.', tip: '' },
      { instruction: 'Fold in chocolate chips. For extra chewy cookies, refrigerate dough for 30 minutes.', tip: 'Chilling the dough prevents spreading and deepens the flavour.' },
      { instruction: 'Drop rounded tablespoons of dough onto prepared baking sheets, spacing 5cm apart.', tip: 'Use a cookie scoop for even sizing and uniform baking.' },
      { instruction: 'Bake 10–12 minutes until edges are golden but centres look slightly underdone.', tip: 'They firm up as they cool — pull them out early for a chewy result.' },
      { instruction: 'Cool on baking sheets for 5 minutes, then transfer to a wire rack.', tip: '' },
    ],
    nutrition: { calories: 195, protein: '2g', carbs: '26g', fat: '9g', fiber: '1g', sugar: '17g' },
    views: 68, saves: 35,
    createdAt: '2025-01-18T08:00:00.000Z',
  },

  {
    id: 'r_seed_005',
    title: 'Buttery Shortbread Fingers',
    category: 'Cookies',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 20,
    servings: 20,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80',
    description: 'Melt-in-your-mouth Scottish shortbread with just three ingredients. Crumbly, buttery perfection.',
    ingredients: [
      { name: 'unsalted butter',      qty: '250g (softened)' },
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'powdered sugar',       qty: '⅓ cup' },
      { name: 'vanilla extract',      qty: '½ tsp' },
      { name: 'salt',                 qty: 'a pinch' },
    ],
    steps: [
      { instruction: 'Preheat oven to 160°C (320°F). Line a baking tray with parchment paper.', tip: 'Low and slow is key to shortbread — high heat makes it hard.' },
      { instruction: 'Beat softened butter and powdered sugar until pale and very fluffy, about 5 minutes. Mix in vanilla.', tip: '' },
      { instruction: 'Sift in flour and salt. Mix until a soft dough forms — do not overwork it.', tip: 'Stop mixing as soon as the flour is incorporated.' },
      { instruction: 'Press dough into a rectangle about 1cm thick on the tray, or roll and cut into finger shapes.', tip: 'Chilling the shaped dough for 15 minutes helps it hold shape in the oven.' },
      { instruction: 'Prick all over with a fork. Bake 18–22 minutes until pale golden — not brown.', tip: '' },
      { instruction: 'While warm, cut into fingers or squares. Cool completely on the tray before moving.', tip: 'Shortbread is fragile when warm but firms up beautifully once cooled.' },
    ],
    nutrition: { calories: 145, protein: '1g', carbs: '14g', fat: '10g', fiber: '0g', sugar: '4g' },
    views: 29, saves: 14,
    createdAt: '2025-01-20T08:00:00.000Z',
  },

  {
    id: 'r_seed_006',
    title: 'Spiced Ginger Snap Cookies',
    category: 'Cookies',
    difficulty: 'Intermediate',
    prepTime: 20,
    bakeTime: 10,
    servings: 36,
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&q=80',
    description: 'Crisp, snappy cookies packed with warm ginger, cinnamon, and cloves. Perfect with a cup of chai.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'unsalted butter',      qty: '¾ cup (softened)' },
      { name: 'granulated sugar',     qty: '1 cup' },
      { name: 'molasses',             qty: '¼ cup' },
      { name: 'large eggs',           qty: '1' },
      { name: 'ground ginger',        qty: '2 tsp' },
      { name: 'ground cinnamon',      qty: '1 tsp' },
      { name: 'ground cloves',        qty: '½ tsp' },
      { name: 'baking soda',          qty: '2 tsp' },
      { name: 'salt',                 qty: '½ tsp' },
    ],
    steps: [
      { instruction: 'Beat butter and ¾ cup sugar until fluffy. Beat in egg and molasses.', tip: '' },
      { instruction: 'Whisk flour, ginger, cinnamon, cloves, baking soda, and salt together. Stir into butter mixture until a dough forms.', tip: 'The dough will be slightly sticky — that is normal.' },
      { instruction: 'Refrigerate dough for at least 1 hour (or overnight).', tip: 'Cold dough rolls more easily and produces a crisper snap.' },
      { instruction: 'Preheat oven to 190°C (375°F). Roll dough into 2cm balls and roll each in remaining sugar.', tip: '' },
      { instruction: 'Place 5cm apart on parchment-lined sheets. Flatten slightly with the bottom of a glass.', tip: '' },
      { instruction: 'Bake 8–10 minutes until the tops are cracked and the edges are set. They will firm up as they cool.', tip: 'Do not overbake — they should still feel slightly soft in the centre when removed.' },
    ],
    nutrition: { calories: 88, protein: '1g', carbs: '13g', fat: '4g', fiber: '0g', sugar: '8g' },
    views: 22, saves: 10,
    createdAt: '2025-01-22T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     BREAD (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_007',
    title: 'Classic Banana Bread',
    category: 'Bread',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 65,
    servings: 10,
    image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&q=80',
    description: 'Moist, tender banana bread with a golden crust. The perfect way to use overripe bananas.',
    ingredients: [
      { name: 'ripe bananas',         qty: '3 large (mashed)' },
      { name: 'all-purpose flour',    qty: '1½ cups' },
      { name: 'granulated sugar',     qty: '¾ cup' },
      { name: 'unsalted butter',      qty: '⅓ cup (melted)' },
      { name: 'large eggs',           qty: '1' },
      { name: 'baking soda',          qty: '1 tsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: '¼ tsp' },
      { name: 'whole milk',           qty: '2 tbsp' },
    ],
    steps: [
      { instruction: 'Preheat oven to 175°C (350°F). Grease a 9x5 inch loaf pan.', tip: '' },
      { instruction: 'In a large bowl, mash the bananas thoroughly with a fork until almost smooth.', tip: 'The riper and more spotted the bananas, the sweeter and more flavourful the bread.' },
      { instruction: 'Stir in melted butter, then mix in sugar, egg, and vanilla.', tip: '' },
      { instruction: 'Add milk and baking soda. Mix in flour and salt until just combined.', tip: 'A few lumps are fine — do not overmix.' },
      { instruction: 'Pour batter into prepared pan. Optionally, slice a banana in half lengthwise and press on top for decoration.', tip: '' },
      { instruction: 'Bake 60–65 minutes until a toothpick inserted in the centre comes out clean.', tip: 'If the top browns too quickly, tent loosely with foil after 40 minutes.' },
      { instruction: 'Cool in pan 15 minutes, then turn out onto a rack. Best sliced when fully cooled.', tip: '' },
    ],
    nutrition: { calories: 210, protein: '3g', carbs: '38g', fat: '6g', fiber: '2g', sugar: '20g' },
    views: 74, saves: 40,
    createdAt: '2025-01-25T08:00:00.000Z',
  },

  {
    id: 'r_seed_008',
    title: 'Rustic No-Knead Sourdough',
    category: 'Bread',
    difficulty: 'Advanced',
    prepTime: 30,
    bakeTime: 45,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80',
    description: 'A crusty, chewy sourdough with an open crumb and deep flavour. Requires an overnight rise but minimal effort.',
    ingredients: [
      { name: 'bread flour',          qty: '3 cups' },
      { name: 'sourdough starter',    qty: '¼ cup (active)' },
      { name: 'warm water',           qty: '1¼ cups' },
      { name: 'salt',                 qty: '1½ tsp' },
      { name: 'olive oil',            qty: '1 tbsp' },
    ],
    steps: [
      { instruction: 'Mix flour, starter, and water in a large bowl until shaggy. Cover and rest 30 minutes (autolyse).', tip: 'The autolyse rest allows gluten to develop without kneading.' },
      { instruction: 'Add salt and olive oil. Mix thoroughly with wet hands.', tip: '' },
      { instruction: 'Perform 4 sets of stretch-and-folds over 2 hours, 30 minutes apart. Cover and bulk ferment at room temperature for 8–12 hours.', tip: 'Cooler rooms = longer ferment. Look for dough to increase 50–75% in size.' },
      { instruction: 'Turn dough onto an unfloured surface. Shape into a round boule, creating surface tension. Place in a floured banneton or bowl lined with a floured cloth.', tip: '' },
      { instruction: 'Refrigerate uncovered for 8–16 hours (cold proof). Meanwhile, preheat oven to 240°C (465°F) with a Dutch oven inside for at least 45 minutes.', tip: 'The cold proof develops flavour and makes scoring easier.' },
      { instruction: 'Turn cold dough onto parchment. Score the top with a lame or sharp knife at a 30° angle.', tip: 'Score confidently in one swift motion for a clean ear.' },
      { instruction: 'Lower into hot Dutch oven. Bake covered 20 minutes, then uncovered 20–25 minutes until deep golden brown. Cool on a wire rack for at least 1 hour before cutting.', tip: 'The interior is still baking as it cools — cutting early will make the crumb gummy.' },
    ],
    nutrition: { calories: 185, protein: '6g', carbs: '36g', fat: '2g', fiber: '2g', sugar: '1g' },
    views: 31, saves: 19,
    createdAt: '2025-01-28T08:00:00.000Z',
  },

  {
    id: 'r_seed_009',
    title: 'Soft Dinner Rolls',
    category: 'Bread',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 20,
    servings: 12,
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&q=80',
    description: 'Cloud-soft, pillowy dinner rolls with a golden butter-brushed top. A guaranteed crowd pleaser.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '3½ cups' },
      { name: 'whole milk',           qty: '1 cup (warm)' },
      { name: 'unsalted butter',      qty: '4 tbsp (softened)' },
      { name: 'granulated sugar',     qty: '3 tbsp' },
      { name: 'large eggs',           qty: '1' },
      { name: 'active dry yeast',     qty: '2¼ tsp (1 packet)' },
      { name: 'salt',                 qty: '1½ tsp' },
    ],
    steps: [
      { instruction: 'In a large bowl, combine warm milk (40°C/105°F), sugar, and yeast. Let sit 5–10 minutes until foamy.', tip: 'If the yeast does not foam, it is dead — start with fresh yeast.' },
      { instruction: 'Add egg, butter, and salt to the yeast mixture. Gradually add flour and mix until a soft dough forms.', tip: '' },
      { instruction: 'Knead dough on a lightly floured surface for 8–10 minutes until smooth and elastic.', tip: 'The dough should pass the windowpane test — stretch a piece thin enough to see light through without tearing.' },
      { instruction: 'Place in a greased bowl, cover, and let rise in a warm place for 1 hour until doubled.', tip: '' },
      { instruction: 'Punch down dough. Divide into 12 equal pieces and roll each into a smooth ball.', tip: 'Use a kitchen scale for perfectly even rolls.' },
      { instruction: 'Arrange in a greased 9x13 inch baking dish. Cover and let rise 45 minutes until puffy and touching.', tip: '' },
      { instruction: 'Preheat oven to 190°C (375°F). Bake 18–22 minutes until golden. Brush immediately with melted butter.', tip: '' },
    ],
    nutrition: { calories: 210, protein: '6g', carbs: '35g', fat: '5g', fiber: '1g', sugar: '5g' },
    views: 44, saves: 26,
    createdAt: '2025-02-01T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     PASTRIES (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_010',
    title: 'Flaky Butter Croissants',
    category: 'Pastries',
    difficulty: 'Advanced',
    prepTime: 120,
    bakeTime: 20,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    description: 'Authentic laminated French croissants with hundreds of paper-thin, buttery layers. A weekend baking project worth every minute.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '3 cups' },
      { name: 'unsalted butter',      qty: '250g (cold, for lamination)' },
      { name: 'whole milk',           qty: '1 cup (warm)' },
      { name: 'granulated sugar',     qty: '3 tbsp' },
      { name: 'active dry yeast',     qty: '2¼ tsp' },
      { name: 'salt',                 qty: '1½ tsp' },
      { name: 'large eggs',           qty: '1 (for egg wash)' },
    ],
    steps: [
      { instruction: 'Mix flour, sugar, salt, and yeast. Add warm milk and mix to a smooth dough. Knead 5 minutes. Wrap in plastic and refrigerate overnight.', tip: 'The slow cold ferment develops flavour and relaxes the gluten for easier lamination.' },
      { instruction: 'Pound cold butter into a flat 15cm square. Keep both butter and dough cold throughout.', tip: 'Butter and dough must be the same temperature — cold but pliable, not hard.' },
      { instruction: 'Roll dough into a rectangle. Place butter in the centre and fold dough over it like an envelope. Seal edges.', tip: '' },
      { instruction: 'Roll out to a long rectangle. Perform a letter fold (3 layers). Wrap and chill 30 minutes. Repeat 2 more times — 3 folds total.', tip: 'Work quickly and chill between folds — if butter starts to melt, refrigerate immediately.' },
      { instruction: 'Roll dough to 5mm thick. Cut into long triangles. Roll each triangle from the wide base to the tip.', tip: 'Stretch the tip gently as you roll for a tighter spiral.' },
      { instruction: 'Place on lined trays, tips tucked under. Proof at room temperature for 2–3 hours until jiggly and doubled.', tip: 'You should see distinct layers when viewing the croissant from the side.' },
      { instruction: 'Brush with egg wash. Bake at 200°C (390°F) for 18–22 minutes until deep golden and caramelised.', tip: 'Do not open the oven in the first 15 minutes — the steam is creating those layers.' },
    ],
    nutrition: { calories: 340, protein: '6g', carbs: '32g', fat: '20g', fiber: '1g', sugar: '6g' },
    views: 48, saves: 28,
    createdAt: '2025-02-04T08:00:00.000Z',
  },

  {
    id: 'r_seed_011',
    title: 'Cream Puffs (Choux Pastry)',
    category: 'Pastries',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 30,
    servings: 16,
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=600&q=80',
    description: 'Light, hollow choux puffs filled with sweetened whipped cream. Elegant and surprisingly simple once you know the technique.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '1 cup' },
      { name: 'unsalted butter',      qty: '½ cup' },
      { name: 'whole milk',           qty: '½ cup' },
      { name: 'water',                qty: '½ cup' },
      { name: 'large eggs',           qty: '4' },
      { name: 'granulated sugar',     qty: '1 tsp' },
      { name: 'salt',                 qty: '¼ tsp' },
      { name: 'heavy cream',          qty: '1½ cups (for filling)' },
      { name: 'powdered sugar',       qty: '3 tbsp (for filling)' },
      { name: 'vanilla extract',      qty: '1 tsp (for filling)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 200°C (390°F). In a saucepan, bring milk, water, butter, sugar, and salt to a rolling boil.', tip: '' },
      { instruction: 'Remove from heat. Add all the flour at once and stir vigorously with a wooden spoon until a smooth dough forms and pulls away from the sides. Return to medium heat and stir 1–2 minutes to dry out.', tip: 'Drying the dough is essential — it lets you incorporate more eggs for a puffier result.' },
      { instruction: 'Transfer to a bowl. Beat in eggs one at a time, mixing completely after each addition. The dough should be glossy and fall in a thick ribbon.', tip: 'You may not need all 4 eggs — stop when the ribbon test is achieved.' },
      { instruction: 'Pipe or spoon 4cm mounds onto a lined baking sheet, spacing well apart. Dampen a finger and smooth any peaks.', tip: '' },
      { instruction: 'Bake 25–30 minutes until deep golden and hollow-sounding when tapped. Do NOT open the oven before 20 minutes.', tip: 'Opening the oven early will collapse the puffs.' },
      { instruction: 'Pierce the side of each puff with a skewer to release steam. Cool completely on a rack.', tip: '' },
      { instruction: 'Whip cream with powdered sugar and vanilla to soft peaks. Fill puffs using a piping bag. Dust with powdered sugar and serve.', tip: 'Fill no more than 30 minutes before serving to keep them crisp.' },
    ],
    nutrition: { calories: 175, protein: '3g', carbs: '11g', fat: '14g', fiber: '0g', sugar: '5g' },
    views: 36, saves: 20,
    createdAt: '2025-02-07T08:00:00.000Z',
  },

  {
    id: 'r_seed_012',
    title: 'Cinnamon Apple Turnovers',
    category: 'Pastries',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 25,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1601000938259-60e09da32b21?w=600&q=80',
    description: 'Flaky puff pastry encasing a warm spiced apple filling. Comfort food at its finest.',
    ingredients: [
      { name: 'puff pastry sheets',   qty: '2 sheets (thawed)' },
      { name: 'apples',               qty: '3 medium (peeled, diced)' },
      { name: 'granulated sugar',     qty: '¼ cup' },
      { name: 'ground cinnamon',      qty: '1½ tsp' },
      { name: 'unsalted butter',      qty: '1 tbsp' },
      { name: 'lemon juice',          qty: '1 tbsp' },
      { name: 'cornstarch',           qty: '1 tbsp' },
      { name: 'large eggs',           qty: '1 (for egg wash)' },
      { name: 'powdered sugar',       qty: '½ cup (for glaze)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 200°C (390°F). Cook apples, sugar, cinnamon, butter, and lemon juice in a saucepan over medium heat for 5 minutes.', tip: '' },
      { instruction: 'Stir in cornstarch and cook 1 more minute until thickened. Remove from heat and cool 10 minutes.', tip: 'The filling must be cooled before using — hot filling makes pastry greasy.' },
      { instruction: 'Unfold pastry sheets on a lightly floured surface. Cut each sheet into 4 squares.', tip: '' },
      { instruction: 'Place a spoonful of filling in the centre of each square. Brush edges with egg wash. Fold diagonally to form triangles. Press edges with a fork to seal.', tip: 'Do not overfill — the filling expands as it bakes.' },
      { instruction: 'Brush tops with egg wash. Cut a small slit in each turnover for steam to escape.', tip: '' },
      { instruction: 'Bake 20–25 minutes until puffed and deep golden brown. Cool on a rack.', tip: '' },
      { instruction: 'Mix powdered sugar with a teaspoon of water to make a drizzleable glaze. Drizzle over warm turnovers.', tip: '' },
    ],
    nutrition: { calories: 285, protein: '4g', carbs: '36g', fat: '14g', fiber: '2g', sugar: '16g' },
    views: 27, saves: 15,
    createdAt: '2025-02-10T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     MUFFINS (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_013',
    title: 'Blueberry Streusel Muffins',
    category: 'Muffins',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 22,
    servings: 12,
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80',
    description: 'Tall, bakery-style muffins bursting with juicy blueberries and crowned with a buttery cinnamon streusel topping.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'granulated sugar',     qty: '¾ cup' },
      { name: 'unsalted butter',      qty: '½ cup (melted)' },
      { name: 'large eggs',           qty: '2' },
      { name: 'whole milk',           qty: '¾ cup' },
      { name: 'fresh blueberries',    qty: '1½ cups' },
      { name: 'baking powder',        qty: '2½ tsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: '½ tsp' },
      { name: 'brown sugar',          qty: '3 tbsp (for streusel)' },
      { name: 'ground cinnamon',      qty: '½ tsp (for streusel)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 190°C (375°F). Line a 12-cup muffin tin with paper liners.', tip: '' },
      { instruction: 'Make streusel: mix 3 tbsp flour, brown sugar, cinnamon, and 2 tbsp cold butter with fingertips until crumbly. Set aside.', tip: '' },
      { instruction: 'In a large bowl, whisk together melted butter, sugar, eggs, milk, and vanilla.', tip: '' },
      { instruction: 'Fold in flour, baking powder, and salt until just combined. Gently fold in blueberries — do not overmix.', tip: 'Toss blueberries in 1 tsp flour before folding — this prevents them from sinking.' },
      { instruction: 'Fill muffin cups ¾ full. Sprinkle streusel generously on top.', tip: 'Mounding the batter tall gives that bakery-style dome.' },
      { instruction: 'Bake 20–22 minutes until a toothpick comes out clean and tops are golden. Cool in pan 5 minutes.', tip: '' },
    ],
    nutrition: { calories: 225, protein: '4g', carbs: '34g', fat: '9g', fiber: '1g', sugar: '18g' },
    views: 52, saves: 31,
    createdAt: '2025-02-13T08:00:00.000Z',
  },

  {
    id: 'r_seed_014',
    title: 'Double Chocolate Muffins',
    category: 'Muffins',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 20,
    servings: 12,
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=600&q=80',
    description: 'Intensely chocolatey muffins with a fudgy interior and chocolate chips throughout. A chocolate lover\'s dream.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '1¾ cups' },
      { name: 'cocoa powder',         qty: '½ cup' },
      { name: 'granulated sugar',     qty: '1 cup' },
      { name: 'unsalted butter',      qty: '½ cup (melted)' },
      { name: 'large eggs',           qty: '2' },
      { name: 'whole milk',           qty: '1 cup' },
      { name: 'chocolate chips',      qty: '1 cup' },
      { name: 'baking powder',        qty: '2 tsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: '½ tsp' },
    ],
    steps: [
      { instruction: 'Preheat oven to 190°C (375°F). Line a 12-cup muffin tin.', tip: '' },
      { instruction: 'Whisk together melted butter, sugar, eggs, milk, and vanilla in a large bowl.', tip: '' },
      { instruction: 'Sift in flour, cocoa powder, baking powder, and salt. Fold until just combined.', tip: 'Lumps are fine — overmixing makes tough muffins.' },
      { instruction: 'Fold in ¾ of the chocolate chips. Fill muffin cups ¾ full.', tip: '' },
      { instruction: 'Sprinkle remaining chocolate chips on top of each muffin.', tip: 'Extra chips on top create a gorgeous molten top as they bake.' },
      { instruction: 'Bake 18–20 minutes. Cool in the tin for 5 minutes before transferring.', tip: '' },
    ],
    nutrition: { calories: 280, protein: '5g', carbs: '38g', fat: '13g', fiber: '2g', sugar: '24g' },
    views: 45, saves: 27,
    createdAt: '2025-02-15T08:00:00.000Z',
  },

  {
    id: 'r_seed_015',
    title: 'Lemon Poppy Seed Muffins',
    category: 'Muffins',
    difficulty: 'Beginner',
    prepTime: 15,
    bakeTime: 20,
    servings: 12,
    image: 'https://images.unsplash.com/photo-1593778034562-39a1c6dc4b78?w=600&q=80',
    description: 'Bright, zingy lemon muffins with a tender crumb and crunchy poppy seeds. Topped with a lemon glaze.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'granulated sugar',     qty: '¾ cup' },
      { name: 'unsalted butter',      qty: '½ cup (melted)' },
      { name: 'large eggs',           qty: '2' },
      { name: 'whole milk',           qty: '¾ cup' },
      { name: 'lemon juice',          qty: '3 tbsp' },
      { name: 'lemon zest',           qty: '2 tbsp' },
      { name: 'poppy seeds',          qty: '2 tbsp' },
      { name: 'baking powder',        qty: '2 tsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: '½ tsp' },
      { name: 'powdered sugar',       qty: '½ cup (for glaze)' },
    ],
    steps: [
      { instruction: 'Preheat oven to 190°C (375°F). Line a 12-cup muffin tin.', tip: '' },
      { instruction: 'Whisk melted butter, sugar, eggs, milk, lemon juice, lemon zest, and vanilla together.', tip: 'Use fresh lemons — the zest is what gives the most intense flavour.' },
      { instruction: 'Fold in flour, baking powder, salt, and poppy seeds until just combined.', tip: '' },
      { instruction: 'Fill muffin cups ¾ full. Bake 18–20 minutes until tops spring back when lightly pressed.', tip: '' },
      { instruction: 'While muffins cool, mix powdered sugar with 1–2 tsp lemon juice to a thick but pourable glaze.', tip: '' },
      { instruction: 'Drizzle glaze over warm muffins. Cool on a rack.', tip: '' },
    ],
    nutrition: { calories: 215, protein: '4g', carbs: '32g', fat: '9g', fiber: '1g', sugar: '18g' },
    views: 33, saves: 18,
    createdAt: '2025-02-17T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     PIES (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_016',
    title: 'Classic Apple Pie',
    category: 'Pies',
    difficulty: 'Intermediate',
    prepTime: 40,
    bakeTime: 55,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1568571780765-9276df97c674?w=600&q=80',
    description: 'A golden, flaky double-crust pie filled with spiced tender apples. The quintessential American comfort dessert.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2½ cups (for crust)' },
      { name: 'unsalted butter',      qty: '1 cup (cold, for crust)' },
      { name: 'ice water',            qty: '6–8 tbsp' },
      { name: 'apples',               qty: '6 large (peeled, sliced)' },
      { name: 'granulated sugar',     qty: '¾ cup' },
      { name: 'brown sugar',          qty: '2 tbsp' },
      { name: 'ground cinnamon',      qty: '1½ tsp' },
      { name: 'ground nutmeg',        qty: '¼ tsp' },
      { name: 'lemon juice',          qty: '1 tbsp' },
      { name: 'cornstarch',           qty: '3 tbsp' },
      { name: 'large eggs',           qty: '1 (for egg wash)' },
      { name: 'salt',                 qty: '½ tsp' },
    ],
    steps: [
      { instruction: 'Make pastry: pulse flour, salt, and cold cubed butter until mixture resembles coarse crumbs. Add ice water one tbsp at a time until dough just comes together. Divide in two, flatten, wrap, refrigerate 1 hour.', tip: 'Keep everything cold — warm butter creates a tough, greasy crust.' },
      { instruction: 'Toss apple slices with sugars, cinnamon, nutmeg, lemon juice, and cornstarch in a large bowl.', tip: '' },
      { instruction: 'Preheat oven to 220°C (425°F). Roll one dough disk to a 30cm circle. Fit into a 9-inch pie dish.', tip: '' },
      { instruction: 'Fill with apple mixture, mounding slightly in the centre. Dot with 1 tbsp butter.', tip: '' },
      { instruction: 'Roll second disk for the top crust. Cover the filling, crimp edges to seal. Cut steam vents. Brush with egg wash.', tip: 'A lattice top is beautiful — weave strips of dough for a classic look.' },
      { instruction: 'Place on a lined baking sheet. Bake at 220°C for 15 minutes, then reduce to 175°C and bake 35–45 more minutes until golden.', tip: 'If edges brown too fast, cover with strips of foil.' },
      { instruction: 'Cool at least 2 hours before serving — this allows the filling to set.', tip: '' },
    ],
    nutrition: { calories: 380, protein: '4g', carbs: '55g', fat: '16g', fiber: '3g', sugar: '30g' },
    views: 39, saves: 23,
    createdAt: '2025-02-20T08:00:00.000Z',
  },

  {
    id: 'r_seed_017',
    title: 'Silky Chocolate Cream Pie',
    category: 'Pies',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 15,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1611516818144-ea18823cf177?w=600&q=80',
    description: 'A crisp Oreo crust filled with lush, pudding-like chocolate cream and topped with freshly whipped cream.',
    ingredients: [
      { name: 'Oreo cookies',         qty: '24 (crushed, for crust)' },
      { name: 'unsalted butter',      qty: '5 tbsp (melted, for crust)' },
      { name: 'dark chocolate',       qty: '200g (chopped)' },
      { name: 'whole milk',           qty: '2½ cups' },
      { name: 'granulated sugar',     qty: '½ cup' },
      { name: 'cornstarch',           qty: '¼ cup' },
      { name: 'large eggs',           qty: '3 yolks' },
      { name: 'unsalted butter',      qty: '2 tbsp (for filling)' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'heavy cream',          qty: '1 cup (for topping)' },
      { name: 'powdered sugar',       qty: '2 tbsp (for topping)' },
    ],
    steps: [
      { instruction: 'Mix Oreo crumbs and melted butter. Press firmly into a 9-inch pie dish. Bake at 175°C for 10 minutes. Cool.', tip: '' },
      { instruction: 'Whisk egg yolks, sugar, and cornstarch in a bowl until pale.', tip: '' },
      { instruction: 'Heat milk in a saucepan until steaming. Slowly whisk hot milk into the egg mixture (tempering). Return all to saucepan.', tip: 'Adding hot milk slowly prevents the eggs from scrambling.' },
      { instruction: 'Cook over medium heat, stirring constantly, until mixture thickens and bubbles for 1 minute. Remove from heat.', tip: '' },
      { instruction: 'Stir in chopped chocolate, butter, and vanilla until completely smooth. Pour into cooled crust.', tip: '' },
      { instruction: 'Press plastic wrap directly on the surface. Refrigerate at least 4 hours or overnight.', tip: 'The plastic wrap prevents a skin from forming on top.' },
      { instruction: 'Whip cream with powdered sugar to soft peaks. Spread over filling. Serve chilled.', tip: '' },
    ],
    nutrition: { calories: 445, protein: '7g', carbs: '48g', fat: '26g', fiber: '2g', sugar: '32g' },
    views: 41, saves: 24,
    createdAt: '2025-02-23T08:00:00.000Z',
  },

  {
    id: 'r_seed_018',
    title: 'Easy Egg Custard Tart',
    category: 'Pies',
    difficulty: 'Beginner',
    prepTime: 20,
    bakeTime: 35,
    servings: 6,
    image: 'https://images.unsplash.com/photo-1611279515544-b0aa395f3cd5?w=600&q=80',
    description: 'Smooth, wobbly egg custard in a crisp shortcrust pastry shell. A beloved British bakery classic.',
    ingredients: [
      { name: 'shortcrust pastry',    qty: '1 sheet (ready-rolled)' },
      { name: 'large eggs',           qty: '3' },
      { name: 'whole milk',           qty: '300ml' },
      { name: 'heavy cream',          qty: '100ml' },
      { name: 'granulated sugar',     qty: '4 tbsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'ground nutmeg',        qty: 'for dusting' },
    ],
    steps: [
      { instruction: 'Preheat oven to 190°C (375°F). Line a 20cm pie or tart tin with shortcrust pastry. Prick the base with a fork. Blind bake with baking beans for 10 minutes. Remove beans and bake 5 more minutes.', tip: 'Blind baking prevents the base from becoming soggy.' },
      { instruction: 'Whisk together eggs, milk, cream, sugar, and vanilla until smooth. Strain through a sieve for extra silkiness.', tip: '' },
      { instruction: 'Reduce oven to 160°C (320°F). Pour custard into the warm pastry shell. Grate a little nutmeg generously over the top.', tip: 'Freshly grated nutmeg is far more fragrant than pre-ground.' },
      { instruction: 'Bake 25–30 minutes until the custard is just set with a slight wobble in the centre.', tip: 'The custard will continue to set as it cools — do not overbake.' },
      { instruction: 'Cool completely before slicing. Serve at room temperature or lightly chilled.', tip: '' },
    ],
    nutrition: { calories: 295, protein: '7g', carbs: '24g', fat: '18g', fiber: '1g', sugar: '14g' },
    views: 28, saves: 16,
    createdAt: '2025-02-26T08:00:00.000Z',
  },

  /* ══════════════════════════════════════════════
     TARTS (3)
  ══════════════════════════════════════════════ */
  {
    id: 'r_seed_019',
    title: 'French Lemon Tart',
    category: 'Tarts',
    difficulty: 'Intermediate',
    prepTime: 40,
    bakeTime: 35,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d5b1ff?w=600&q=80',
    description: 'A crisp buttery pastry shell filled with intensely tangy, velvety lemon curd. Pâtisserie perfection.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '1½ cups (for pastry)' },
      { name: 'unsalted butter',      qty: '½ cup + 4 tbsp' },
      { name: 'powdered sugar',       qty: '¼ cup (for pastry)' },
      { name: 'large eggs',           qty: '4 (2 for pastry, 2 for filling)' },
      { name: 'lemon juice',          qty: '½ cup (fresh)' },
      { name: 'lemon zest',           qty: '2 tbsp' },
      { name: 'granulated sugar',     qty: '¾ cup (for filling)' },
      { name: 'heavy cream',          qty: '⅓ cup' },
      { name: 'salt',                 qty: 'a pinch' },
    ],
    steps: [
      { instruction: 'Make pâte sucrée: beat ½ cup butter and powdered sugar until pale. Beat in 2 egg yolks. Add flour and salt, mix until dough just comes together. Flatten, wrap, chill 30 minutes.', tip: '' },
      { instruction: 'Roll dough to 3mm and line a 23cm tart tin. Chill 15 minutes. Blind bake at 190°C for 15 minutes with baking beans, then 5 minutes uncovered until pale gold.', tip: '' },
      { instruction: 'Whisk 2 whole eggs, 2 yolks, granulated sugar, lemon juice, and zest in a saucepan. Cook over low heat, stirring constantly.', tip: 'Never stop stirring — eggs will scramble if the heat is too high.' },
      { instruction: 'When the mixture thickens and coats the back of a spoon (about 75°C), remove from heat. Stir in remaining butter cube by cube.', tip: '' },
      { instruction: 'Strain the curd through a fine sieve. Whisk in the cream. Pour into the warm tart shell.', tip: 'Straining gives an ultra-smooth, glossy curd.' },
      { instruction: 'Reduce oven to 160°C. Bake 8–10 minutes until curd is just set with a slight wobble. Cool completely.', tip: '' },
      { instruction: 'Chill at least 2 hours before serving. Garnish with thin lemon slices or powdered sugar.', tip: '' },
    ],
    nutrition: { calories: 360, protein: '5g', carbs: '38g', fat: '21g', fiber: '1g', sugar: '24g' },
    views: 37, saves: 21,
    createdAt: '2025-03-01T08:00:00.000Z',
  },

  {
    id: 'r_seed_020',
    title: 'Strawberry Jam Tart',
    category: 'Tarts',
    difficulty: 'Beginner',
    prepTime: 20,
    bakeTime: 25,
    servings: 8,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80',
    description: 'A classic lattice-topped jam tart with a crumbly shortcrust base and sweet strawberry filling. Childhood nostalgia in every bite.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '2 cups' },
      { name: 'unsalted butter',      qty: '½ cup (cold)' },
      { name: 'powdered sugar',       qty: '¼ cup' },
      { name: 'large eggs',           qty: '1' },
      { name: 'strawberry jam',       qty: '1 cup' },
      { name: 'vanilla extract',      qty: '½ tsp' },
      { name: 'salt',                 qty: 'a pinch' },
      { name: 'cold water',           qty: '1–2 tbsp' },
    ],
    steps: [
      { instruction: 'Rub cold butter into flour, sugar, and salt until breadcrumb-like. Mix in egg and vanilla. Add water if needed to bring dough together. Chill 20 minutes.', tip: '' },
      { instruction: 'Preheat oven to 180°C (355°F). Roll ⅔ of dough and line a 23cm tart tin. Prick base.', tip: '' },
      { instruction: 'Spread strawberry jam evenly over the pastry base.', tip: 'Warm the jam briefly to make it easier to spread.' },
      { instruction: 'Roll remaining dough and cut into strips. Weave a lattice pattern on top of the jam. Trim and seal edges.', tip: '' },
      { instruction: 'Bake 22–25 minutes until pastry is golden and jam is bubbling.', tip: '' },
      { instruction: 'Cool in the tin before slicing. Serve with clotted cream or vanilla ice cream.', tip: '' },
    ],
    nutrition: { calories: 310, protein: '4g', carbs: '46g', fat: '13g', fiber: '1g', sugar: '26g' },
    views: 25, saves: 13,
    createdAt: '2025-03-04T08:00:00.000Z',
  },

  {
    id: 'r_seed_021',
    title: 'Chocolate Ganache Tart',
    category: 'Tarts',
    difficulty: 'Intermediate',
    prepTime: 30,
    bakeTime: 20,
    servings: 10,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    description: 'An intensely rich chocolate ganache in a crisp cocoa pastry shell. Simple, sophisticated, and absolutely irresistible.',
    ingredients: [
      { name: 'all-purpose flour',    qty: '1¼ cups (for pastry)' },
      { name: 'cocoa powder',         qty: '2 tbsp (for pastry)' },
      { name: 'unsalted butter',      qty: '½ cup cold + 2 tbsp' },
      { name: 'powdered sugar',       qty: '3 tbsp' },
      { name: 'large eggs',           qty: '1 yolk (for pastry)' },
      { name: 'dark chocolate (70%)', qty: '300g (chopped)' },
      { name: 'heavy cream',          qty: '300ml' },
      { name: 'honey',                qty: '1 tbsp' },
      { name: 'vanilla extract',      qty: '1 tsp' },
      { name: 'salt',                 qty: 'a pinch' },
      { name: 'flaked sea salt',      qty: 'for topping' },
    ],
    steps: [
      { instruction: 'Make chocolate pastry: mix flour, cocoa, powdered sugar, and salt. Rub in cold butter. Stir in egg yolk and 1–2 tbsp cold water until dough comes together. Chill 30 minutes.', tip: '' },
      { instruction: 'Roll dough to 3mm, line a 23cm tart tin. Chill 15 minutes. Blind bake at 190°C for 12 minutes, remove beans, bake 5 more minutes. Cool.', tip: '' },
      { instruction: 'Bring cream, honey, and a pinch of salt to a gentle simmer. Remove from heat.', tip: '' },
      { instruction: 'Pour hot cream over chopped chocolate. Let sit 2 minutes, then stir from the centre outwards in slow, calm circles until glossy and smooth. Stir in vanilla.', tip: 'Stirring slowly from the centre prevents air bubbles.' },
      { instruction: 'Pour ganache into the cooled tart shell. Gently tap the tin on the counter to level the surface.', tip: '' },
      { instruction: 'Sprinkle flaked sea salt over the top. Refrigerate for at least 3 hours until set.', tip: 'The salt enhances the chocolate flavour dramatically.' },
      { instruction: 'Remove from fridge 20 minutes before serving for the best texture. Slice with a warm knife.', tip: 'Dip the knife in hot water and wipe dry between cuts for clean slices.' },
    ],
    nutrition: { calories: 395, protein: '5g', carbs: '32g', fat: '28g', fiber: '3g', sugar: '20g' },
    views: 43, saves: 25,
    createdAt: '2025-03-07T08:00:00.000Z',
  },

];

/* ============================================================
   INIT — Seeds data only on first visit (checks for existing)
   ============================================================ */
function initSeedData() {
  const existing = storageGet(KEYS.RECIPES, []);

  /* Only seed if no recipes exist yet */
  if (existing.length === 0) {
    storageSet(KEYS.RECIPES, SEED_RECIPES);
    console.log(`[Pantry-to-Oven] Seeded ${SEED_RECIPES.length} recipes.`);
  }

  /* Ensure admin session key exists (just the constant — no storage) */
  /* Admin credentials are hardcoded: admin / admin123 */
}
